Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Exclude:
    - "lib/img_lint/linter.rb"

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/AbcSize:
  Max: 25
