Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Exclude:
    - "lib/img_lint/linter.rb"

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Max: 60

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "lib/img_lint/cli.rb"
